export const medmkpSuppliers = [
  {
    id: "msup_integrated_medical",
    name: "Integrated Medical",
    slug: "integrated-medical",
    website_url: "https://integratedmedicalonline.com",
    support_email: "orders@integratedmedical.example",
    onboarding_status: "approved",
    ein_last_four: "4821",
    certification_summary: "PT, rehab, and clinical therapy supplies distributor",
    default_lead_time_days: 4,
    ach_enabled: true,
  },
  {
    id: "msup_therapy_direct",
    name: "Therapy Direct Supply",
    slug: "therapy-direct-supply",
    website_url: "https://example.com/therapy-direct",
    support_email: "quotes@therapydirect.example",
    onboarding_status: "in_review",
    ein_last_four: "1934",
    certification_summary: "Rehab consumables and durable therapy equipment",
    default_lead_time_days: 6,
    ach_enabled: false,
  },
]

export const medmkpCanonicalProducts = [
  {
    handle: "therapy-band-roll-latex-free-medium-50yd",
    title: "Therapy Band Roll, Latex-Free, Medium Resistance, 50 yd",
    category: "Therapy bands",
    subtitle: "Canonical therapy band product for PT and rehab reorder matching",
    description:
      "Latex-free medium-resistance therapy band roll used for strengthening and home exercise programs.",
    unit: "Roll",
  },
  {
    handle: "kinesiology-tape-2in-16ft-case",
    title: "Kinesiology Tape, 2 in x 16 ft, Case of 6",
    category: "Tape",
    subtitle: "Canonical kinesiology tape case",
    description:
      "Clinic-grade kinesiology tape case for sports medicine, rehab, and chiropractic treatment plans.",
    unit: "Case",
  },
  {
    handle: "reusable-electrodes-2x2-pack-40",
    title: "Reusable Electrodes, 2 x 2 in, Pack of 40",
    category: "Electrodes",
    subtitle: "Canonical reusable electrode pack",
    description:
      "Reusable electrodes for common electrotherapy and stimulation workflows in rehab clinics.",
    unit: "Pack",
  },
  {
    handle: "exam-table-paper-smooth-21in-case",
    title: "Exam Table Paper, Smooth, 21 in x 225 ft, Case of 12",
    category: "Table paper",
    subtitle: "Canonical smooth exam table paper case",
    description:
      "Smooth exam table paper for PT, chiropractic, and rehab treatment tables.",
    unit: "Case",
  },
  {
    handle: "nitrile-exam-gloves-medium-1000ct",
    title: "Nitrile Exam Gloves, Medium, 1,000 ct",
    category: "Gloves",
    subtitle: "Canonical medium nitrile glove case",
    description:
      "Powder-free medium nitrile exam gloves for clinical treatment environments.",
    unit: "Case",
  },
  {
    handle: "healthcare-disinfectant-wipes-case",
    title: "Disinfectant Wipes, Healthcare Grade, 160 ct, Case of 12",
    category: "Disinfectant wipes",
    subtitle: "Canonical healthcare disinfectant wipe case",
    description:
      "Healthcare-grade disinfectant wipes for treatment tables, equipment, and high-touch surfaces.",
    unit: "Case",
  },
  {
    handle: "reusable-hot-cold-pack-standard-case",
    title: "Reusable Hot/Cold Pack, Standard, Case of 12",
    category: "Hot/cold packs",
    subtitle: "Canonical reusable hot/cold pack case",
    description:
      "Reusable standard-size hot/cold packs for clinic treatment rooms.",
    unit: "Case",
  },
  {
    handle: "disposable-face-cradle-covers-100ct",
    title: "Disposable Face Cradle Covers, 100 ct",
    category: "Face cradle covers",
    subtitle: "Canonical disposable face cradle cover pack",
    description:
      "Disposable face cradle covers for chiropractic and massage-style treatment tables.",
    unit: "Pack",
  },
  {
    handle: "clinic-hand-towels-16x27-24ct",
    title: "Clinic Hand Towels, 16 x 27 in, 24 ct",
    category: "Towels",
    subtitle: "Canonical reusable clinic towel pack",
    description:
      "Reusable clinic hand towels for therapy rooms, treatment cleanup, and hot/cold therapy workflows.",
    unit: "Pack",
  },
  {
    handle: "foam-roller-6x36-medium-density",
    title: "Foam Roller, 6 x 36 in, Medium Density",
    category: "Foam rollers",
    subtitle: "Canonical medium-density foam roller",
    description:
      "Medium-density full-size foam roller for mobility, stretching, and rehab exercise programs.",
    unit: "Each",
  },
]

export const medmkpCatalogItems = [
  {
    id: "mcat_integrated_therapy_band",
    supplier_id: "msup_integrated_medical",
    medusa_product_handle: "therapy-band-roll-latex-free-medium-50yd",
    canonical_name: "Therapy Band Roll, Latex-Free, Medium Resistance, 50 yd",
    canonical_category: "Therapy bands",
    sku: "IM-BAND-MED-LF-50YD",
    manufacturer: "TheraBand",
    brand: "TheraBand",
    name: "Therapy Band Roll, Blue, 50 yd",
    category: "Therapy bands",
    unit_of_measure: "roll",
    unit_price_cents: 5799,
    comparable_score: 97,
    lead_time_days: 3,
    inventory_status: "in_stock",
    exact_brand_required: false,
  },
  {
    id: "mcat_therapy_direct_band",
    supplier_id: "msup_therapy_direct",
    medusa_product_handle: "therapy-band-roll-latex-free-medium-50yd",
    canonical_name: "Therapy Band Roll, Latex-Free, Medium Resistance, 50 yd",
    canonical_category: "Therapy bands",
    sku: "TD-BAND-MED-50",
    manufacturer: "CanDo",
    brand: "CanDo",
    name: "Latex-Free Exercise Band Roll, Medium, 50 yd",
    category: "Therapy bands",
    unit_of_measure: "roll",
    unit_price_cents: 6125,
    comparable_score: 91,
    lead_time_days: 5,
    inventory_status: "in_stock",
    exact_brand_required: false,
  },
  {
    id: "mcat_integrated_kinesiology_tape",
    supplier_id: "msup_integrated_medical",
    medusa_product_handle: "kinesiology-tape-2in-16ft-case",
    canonical_name: "Kinesiology Tape, 2 in x 16 ft, Case of 6",
    canonical_category: "Tape",
    sku: "IM-KTAPE-2IN-CASE6",
    manufacturer: "KT Tape",
    brand: "KT Tape",
    name: "Kinesiology Tape, 2 in x 16 ft, Case of 6",
    category: "Tape",
    unit_of_measure: "case",
    unit_price_cents: 7499,
    comparable_score: 93,
    lead_time_days: 4,
    inventory_status: "in_stock",
    exact_brand_required: false,
  },
  {
    id: "mcat_therapy_direct_electrodes",
    supplier_id: "msup_therapy_direct",
    medusa_product_handle: "reusable-electrodes-2x2-pack-40",
    canonical_name: "Reusable Electrodes, 2 x 2 in, Pack of 40",
    canonical_category: "Electrodes",
    sku: "TD-ELEC-2X2-40",
    manufacturer: "Axelgaard",
    brand: "PALS",
    name: "Reusable Electrodes, 2 x 2 in, Pack of 40",
    category: "Electrodes",
    unit_of_measure: "pack",
    unit_price_cents: 2895,
    comparable_score: 95,
    lead_time_days: 3,
    inventory_status: "in_stock",
    exact_brand_required: false,
  },
  {
    id: "mcat_integrated_table_paper",
    supplier_id: "msup_integrated_medical",
    medusa_product_handle: "exam-table-paper-smooth-21in-case",
    canonical_name: "Exam Table Paper, Smooth, 21 in x 225 ft, Case of 12",
    canonical_category: "Table paper",
    sku: "IM-TABLE-PAPER-21-12",
    manufacturer: "Tidi",
    brand: "Tidi",
    name: "Smooth Exam Table Paper, 21 in x 225 ft, Case of 12",
    category: "Table paper",
    unit_of_measure: "case",
    unit_price_cents: 6495,
    comparable_score: 90,
    lead_time_days: 4,
    inventory_status: "limited",
    exact_brand_required: false,
  },
  {
    id: "mcat_therapy_direct_gloves",
    supplier_id: "msup_therapy_direct",
    medusa_product_handle: "nitrile-exam-gloves-medium-1000ct",
    canonical_name: "Nitrile Exam Gloves, Medium, 1,000 ct",
    canonical_category: "Gloves",
    sku: "TD-NITRILE-MED-1000",
    manufacturer: "Aurelia",
    brand: "Aurelia",
    name: "Nitrile Exam Gloves, Medium, 1,000 ct",
    category: "Gloves",
    unit_of_measure: "case",
    unit_price_cents: 11900,
    comparable_score: 88,
    lead_time_days: 6,
    inventory_status: "in_stock",
    exact_brand_required: true,
  },
  {
    id: "mcat_integrated_wipes",
    supplier_id: "msup_integrated_medical",
    medusa_product_handle: "healthcare-disinfectant-wipes-case",
    canonical_name: "Disinfectant Wipes, Healthcare Grade, 160 ct, Case of 12",
    canonical_category: "Disinfectant wipes",
    sku: "IM-WIPES-HC-160-12",
    manufacturer: "PDI",
    brand: "Sani-Cloth",
    name: "Healthcare Disinfectant Wipes, 160 ct, Case of 12",
    category: "Disinfectant wipes",
    unit_of_measure: "case",
    unit_price_cents: 10450,
    comparable_score: 94,
    lead_time_days: 3,
    inventory_status: "in_stock",
    exact_brand_required: false,
  },
  {
    id: "mcat_integrated_hot_cold_pack",
    supplier_id: "msup_integrated_medical",
    medusa_product_handle: "reusable-hot-cold-pack-standard-case",
    canonical_name: "Reusable Hot/Cold Pack, Standard, Case of 12",
    sku: "IM-CP-STD-12",
    manufacturer: "Core Products",
    brand: "Core",
    name: "Reusable Hot/Cold Pack, Standard, Case of 12",
    canonical_category: "Hot/cold packs",
    category: "Hot/cold packs",
    unit_of_measure: "case",
    unit_price_cents: 8425,
    comparable_score: 91,
    lead_time_days: 4,
    inventory_status: "limited",
    exact_brand_required: false,
  },
  {
    id: "mcat_therapy_direct_face_cradle",
    supplier_id: "msup_therapy_direct",
    medusa_product_handle: "disposable-face-cradle-covers-100ct",
    canonical_name: "Disposable Face Cradle Covers, 100 ct",
    canonical_category: "Face cradle covers",
    sku: "TD-FACE-COVER-100",
    manufacturer: "BodyMed",
    brand: "BodyMed",
    name: "Disposable Face Cradle Covers, 100 ct",
    category: "Face cradle covers",
    unit_of_measure: "pack",
    unit_price_cents: 1795,
    comparable_score: 89,
    lead_time_days: 4,
    inventory_status: "in_stock",
    exact_brand_required: false,
  },
  {
    id: "mcat_integrated_towels",
    supplier_id: "msup_integrated_medical",
    medusa_product_handle: "clinic-hand-towels-16x27-24ct",
    canonical_name: "Clinic Hand Towels, 16 x 27 in, 24 ct",
    canonical_category: "Towels",
    sku: "IM-TOWEL-16X27-24",
    manufacturer: "Medline",
    brand: "Medline",
    name: "Clinic Hand Towels, 16 x 27 in, 24 ct",
    category: "Towels",
    unit_of_measure: "pack",
    unit_price_cents: 3895,
    comparable_score: 87,
    lead_time_days: 5,
    inventory_status: "limited",
    exact_brand_required: false,
  },
  {
    id: "mcat_therapy_direct_foam_roller",
    supplier_id: "msup_therapy_direct",
    medusa_product_handle: "foam-roller-6x36-medium-density",
    canonical_name: "Foam Roller, 6 x 36 in, Medium Density",
    canonical_category: "Foam rollers",
    sku: "TD-FOAM-6X36-MD",
    manufacturer: "OPTP",
    brand: "OPTP",
    name: "Foam Roller, 6 x 36 in, Medium Density",
    category: "Foam rollers",
    unit_of_measure: "each",
    unit_price_cents: 2495,
    comparable_score: 92,
    lead_time_days: 4,
    inventory_status: "in_stock",
    exact_brand_required: false,
  },
]

export const medmkpRequests = [
  {
    id: "mpr_northline_rehab_june",
    buyer_name: "Northline Rehab",
    buyer_facility_type: "rehab",
    buyer_email: "ops@northlinerehab.example",
    status: "quoted",
    source_file_name: "northline-june-reorder.pdf",
    item_count: 6,
    target_savings_percent: 12,
    notes: "Buyer is flexible on commodity therapy supplies but wants exact nitrile glove brand.",
  },
]

export const medmkpQuotes = [
  {
    id: "mq_northline_best_value",
    procurement_request_id: "mpr_northline_rehab_june",
    supplier_id: "msup_integrated_medical",
    status: "sent",
    subtotal_cents: 128450,
    estimated_shipping_cents: 1795,
    platform_fee_cents: 3854,
    estimated_savings_cents: 18420,
    lead_time_days: 4,
    replacement_policy: "concierge_recommended",
  },
]

export const medmkpCategories = [
  "Therapy bands",
  "Tape",
  "Electrodes",
  "Table paper",
  "Gloves",
  "Disinfectant wipes",
  "Hot/cold packs",
  "Face cradle covers",
  "Towels",
  "Foam rollers",
].map((name) => {
  const categoryItems = medmkpCatalogItems.filter(
    (item) => item.canonical_category === name
  )
  const bestValueItem = categoryItems.sort(
    (a, b) => b.comparable_score - a.comparable_score
  )[0]

  return {
    id: name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""),
    name,
    best_value_item_id: bestValueItem?.id,
    supplier_count: new Set(categoryItems.map((item) => item.supplier_id)).size,
    reorder_frequency:
      name === "Gloves" || name === "Disinfectant wipes" ? "weekly" : "monthly",
  }
})
